dataset_name: BMMC_s1d1
dataset_dir: ../data/BMMC_s1d1/
dataset_type: RNA_ATAC
GAM_name: Signac
paired: True

n_high_var: 2000
hid_dim: 256
neighbors_mnn: 200
metric: cosine
use_rep: hvg_count #[hvg_count, hvg_norm, low_emb]
latent_dim: 32
k_neighbors: 10
k_clusters: 21

seed: 666
batch_size: 256
learning_rate: 0.003
weight_decay: 0.00001

epoch: 450
